version: '3.8'

services:
  api:
    build:
      context: ./SimpleStockMarket.API
      dockerfile: Dockerfile.Deploy
    ports:
      - "5000:8080"
    networks:
      - dashboard-network

  ui:
    build:
      context: ./SimpleStockMarket.UI
      dockerfile: Dockerfile.Deploy
    ports:
      - "5001:80"
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
